### ISSUE TITLE
Can't select after opening the menu

### ISSUE THREAD

**Issue by maciejmyslinski** [romgain/react-select-event#65]
I have this testing scenario: I want to make sure options 'a', 'b', and 'c' exist. Then I want to select option 'a'. One way of doing that could be:
```tsx
selectEvent.openMenu(selectElement)
screen.getByText('a')
screen.getByText('b')
screen.getByText('c')
selectEvent.select(selectElement, 'a')
```

Except that will fail with:
```
TypeError: Cannot read property 'createEvent' of null
    at Object.invokeGuardedCallbackDev (node_modules/react-dom/cjs/react-dom.development.js:3905:26)
    at invokeGuardedCallback (node_modules/react-dom/cjs/react-dom.development.js:4056:31)
    at flushPassiveEffectsImpl (node_modules/react-dom/cjs/react-dom.development.js:23543:11)
    at unstable_runWithPriority (node_modules/scheduler/cjs/scheduler.development.js:646:12)
    at runWithPriority$1 (node_modules/react-dom/cjs/react-dom.development.js:11276:10)
    at flushPassiveEffects (node_modules/react-dom/cjs/react-dom.development.js:23447:14)
    at Object.<anonymous>.flushWork (node_modules/react-dom/cjs/react-dom-test-utils.development.js:992:10)
    at Immediate.<anonymous> (fifteen5/node_modules/react-dom/cjs/react-dom-test-utils.development.js:1003:11)
    at processImmediate (node:internal/timers:462:21)
```

apparently you can't select an option when the menu is opened.
A workaround I used is to fire an esc key event before the option selection:
```tsx
userEvent.type(selectElement, '{esc}');
```

Ideally, the `.select` method can deal with an opened menu properly.

**Comment by romgain** [comment]
Hey @maciejmyslinski !

I understand your use case, but in this particular example, it just looks like a better test would be to select all three options? That way you're not only asserting that the text is present, but also that it is a valid, selectable option.

eg:

```js
// check that all options are correctly populated and selectable:
selectEvent.select(selectElement, 'a');
selectEvent.select(selectElement, 'b');
selectEvent.select(selectElement, 'c');

// select a:
selectEvent.select(selectElement, 'a');
```

**Comment by maciejmyslinski** [comment]
Turns out I forgot the `await` 🤦‍♂️ 

This passes:
```tsx
selectEvent.openMenu(selectElement)
screen.getByText('a')
screen.getByText('b')
screen.getByText('c')
await selectEvent.select(selectElement, 'a')
```

Thank you for quick responses ✌️

**Comment by romgain** [comment]
No probs, glad it worked!
